server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_management
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "0211"
  redis:
    host:  120.26.64.30
    password: lyx0211
    port: 12301